import type { ApplicationStatus } from '@/lib/types';

/**
 * Seed rows for the shared demo account.
 *
 * Dates are stored as offsets, not literals, so the demo never looks stale:
 * `daysAgo` becomes applied_at/created_at, and `progressDays` becomes the gap
 * to updated_at. That gap is what the stage_timing() RPC averages, so the
 * Analytics "TIMING" panel needs it to be non-zero for interviewing/offer rows.
 */
export interface DemoApplication {
  company: string;
  role: string;
  status: ApplicationStatus;
  location: string | null;
  salary_range: string | null;
  job_url: string | null;
  notes: string | null;
  daysAgo: number;
  progressDays: number;
}

export const DEMO_APPLICATIONS: DemoApplication[] = [
  // ---- Rejected: the oldest end of the pipeline -----------------------------
  {
    company: 'Monzo',
    role: 'Graduate Software Engineer',
    status: 'rejected',
    location: 'London',
    salary_range: '£45,000 – £55,000',
    job_url: 'https://monzo.com/careers/graduate-software-engineer',
    notes: 'Two take-home rounds. Rejected after the systems design pairing session.',
    daysAgo: 83,
    progressDays: 18,
  },
  {
    company: 'Ocado Technology',
    role: 'Junior Software Engineer',
    status: 'rejected',
    location: 'Hatfield',
    salary_range: '£38,000 – £45,000',
    job_url: 'https://careers.ocadogroup.com/junior-software-engineer',
    notes: 'Online assessment passed, no interview offered.',
    daysAgo: 80,
    progressDays: 12,
  },
  {
    company: 'Deloitte',
    role: 'Technology Analyst',
    status: 'rejected',
    location: 'London',
    salary_range: '£32,000 – £36,000',
    job_url: null,
    notes: 'Withdrew — scope was closer to consulting than engineering.',
    daysAgo: 76,
    progressDays: 9,
  },
  {
    company: 'Sky',
    role: 'Graduate Developer',
    status: 'rejected',
    location: 'Leeds',
    salary_range: '£34,000 – £40,000',
    job_url: 'https://careers.sky.com/graduate-developer',
    notes: 'Assessment centre — strong feedback on the group exercise, no offer.',
    daysAgo: 71,
    progressDays: 21,
  },
  {
    company: 'Bloomberg',
    role: 'Software Engineer, Graduate',
    status: 'rejected',
    location: 'London',
    salary_range: '£60,000 – £70,000',
    job_url: 'https://careers.bloomberg.com/software-engineer-graduate',
    notes: 'Two technical phone screens. Fell short on the C++ round.',
    daysAgo: 66,
    progressDays: 14,
  },
  {
    company: 'Trainline',
    role: 'Junior Backend Engineer',
    status: 'rejected',
    location: 'London',
    salary_range: '£42,000 – £50,000',
    job_url: 'https://www.trainline.careers/junior-backend-engineer',
    notes: 'Role put on hold, then closed.',
    daysAgo: 58,
    progressDays: 16,
  },
  {
    company: 'Arm',
    role: 'Graduate Software Engineer',
    status: 'rejected',
    location: 'Cambridge',
    salary_range: '£40,000 – £46,000',
    job_url: 'https://careers.arm.com/graduate-software-engineer',
    notes: 'Wanted more embedded experience.',
    daysAgo: 47,
    progressDays: 11,
  },
  {
    company: 'Babylon Health',
    role: 'Junior Full-Stack Engineer',
    status: 'rejected',
    location: 'London (Hybrid)',
    salary_range: '£40,000 – £48,000',
    job_url: null,
    notes: 'Hiring freeze announced a week after the first interview.',
    daysAgo: 39,
    progressDays: 8,
  },

  // ---- Offers ---------------------------------------------------------------
  {
    company: 'Starling Bank',
    role: 'Junior Backend Engineer (Java)',
    status: 'offer',
    location: 'Cardiff / Remote',
    salary_range: '£48,000 – £58,000',
    job_url: 'https://www.starlingbank.com/careers/junior-backend-engineer',
    notes: 'Offer at £54k + 10% bonus. Deciding by the end of the week.',
    daysAgo: 45,
    progressDays: 31,
  },
  {
    company: 'Zopa',
    role: 'Graduate Software Engineer',
    status: 'offer',
    location: 'London (Hybrid)',
    salary_range: '£45,000 – £52,000',
    job_url: 'https://jobs.zopa.com/graduate-software-engineer',
    notes: 'Verbal offer at £50k, written contract pending.',
    daysAgo: 38,
    progressDays: 26,
  },

  // ---- Interviewing ---------------------------------------------------------
  {
    company: 'Revolut',
    role: 'Junior Backend Engineer',
    status: 'interviewing',
    location: 'London',
    salary_range: '£55,000 – £65,000',
    job_url: 'https://www.revolut.com/careers/junior-backend-engineer',
    notes: 'Final round with the payments team on Thursday.',
    daysAgo: 30,
    progressDays: 15,
  },
  {
    company: 'Wise',
    role: 'Graduate Software Engineer',
    status: 'interviewing',
    location: 'London',
    salary_range: '£50,000 – £58,000',
    job_url: 'https://www.wise.jobs/graduate-software-engineer',
    notes: 'Take-home submitted. System design round scheduled.',
    daysAgo: 27,
    progressDays: 12,
  },
  {
    company: 'Depop',
    role: 'Junior Frontend Engineer',
    status: 'interviewing',
    location: 'London (Hybrid)',
    salary_range: '£45,000 – £52,000',
    job_url: 'https://www.depop.com/careers/junior-frontend-engineer',
    notes: 'React pairing exercise went well. Waiting on culture round.',
    daysAgo: 24,
    progressDays: 14,
  },
  {
    company: 'Cloudflare',
    role: 'Systems Engineer, Graduate',
    status: 'interviewing',
    location: 'London',
    salary_range: '£52,000 – £60,000',
    job_url: 'https://www.cloudflare.com/careers/systems-engineer-graduate',
    notes: 'Recruiter screen done. Two technical rounds to go.',
    daysAgo: 21,
    progressDays: 9,
  },
  {
    company: 'Palantir',
    role: 'Software Engineer, New Grad',
    status: 'interviewing',
    location: 'London',
    salary_range: '£70,000 – £80,000',
    job_url: 'https://www.palantir.com/careers/software-engineer-new-grad',
    notes: 'Passed the decomposition round. Onsite loop being scheduled.',
    daysAgo: 17,
    progressDays: 10,
  },
  {
    company: 'Snyk',
    role: 'Junior Security Engineer',
    status: 'interviewing',
    location: 'London (Remote)',
    salary_range: '£48,000 – £56,000',
    job_url: 'https://snyk.io/careers/junior-security-engineer',
    notes: 'Referred by a former coursemate. First interview this week.',
    daysAgo: 13,
    progressDays: 7,
  },

  // ---- Applied: the live top of the funnel ---------------------------------
  {
    company: 'GoCardless',
    role: 'Graduate Software Engineer',
    status: 'applied',
    location: 'London',
    salary_range: '£48,000 – £55,000',
    job_url: 'https://gocardless.com/careers/graduate-software-engineer',
    notes: 'Applied through the grad scheme portal.',
    daysAgo: 20,
    progressDays: 0,
  },
  {
    company: 'Improbable',
    role: 'Junior Platform Engineer',
    status: 'applied',
    location: 'London',
    salary_range: '£50,000 – £60,000',
    job_url: 'https://www.improbable.io/careers/junior-platform-engineer',
    notes: null,
    daysAgo: 18,
    progressDays: 0,
  },
  {
    company: 'Skyscanner',
    role: 'Graduate Software Engineer',
    status: 'applied',
    location: 'Edinburgh',
    salary_range: '£42,000 – £50,000',
    job_url: 'https://www.skyscanner.net/careers/graduate-software-engineer',
    notes: 'Cover letter tailored to their travel data platform.',
    daysAgo: 16,
    progressDays: 0,
  },
  {
    company: 'ASOS',
    role: 'Junior Software Engineer',
    status: 'applied',
    location: 'London (Hybrid)',
    salary_range: '£40,000 – £47,000',
    job_url: 'https://www.asoscareers.com/junior-software-engineer',
    notes: null,
    daysAgo: 15,
    progressDays: 0,
  },
  {
    company: 'Octopus Energy',
    role: 'Junior Python Developer',
    status: 'applied',
    location: 'London',
    salary_range: '£45,000 – £55,000',
    job_url: 'https://octopus.energy/careers/junior-python-developer',
    notes: 'Kraken platform team. Django-heavy stack.',
    daysAgo: 13,
    progressDays: 0,
  },
  {
    company: 'Darktrace',
    role: 'Graduate Cyber Analyst',
    status: 'applied',
    location: 'Cambridge',
    salary_range: '£38,000 – £45,000',
    job_url: 'https://www.darktrace.com/careers/graduate-cyber-analyst',
    notes: 'Good fit with the security module from final year.',
    daysAgo: 12,
    progressDays: 0,
  },
  {
    company: 'Elastic',
    role: 'Junior Software Engineer',
    status: 'applied',
    location: 'Remote (UK)',
    salary_range: '£50,000 – £58,000',
    job_url: 'https://jobs.elastic.co/junior-software-engineer',
    notes: 'Fully distributed team.',
    daysAgo: 11,
    progressDays: 0,
  },
  {
    company: 'Checkout.com',
    role: 'Graduate Backend Engineer',
    status: 'applied',
    location: 'London',
    salary_range: '£55,000 – £62,000',
    job_url: 'https://www.checkout.com/careers/graduate-backend-engineer',
    notes: null,
    daysAgo: 10,
    progressDays: 0,
  },
  {
    company: 'BAE Systems Digital Intelligence',
    role: 'Graduate Software Engineer',
    status: 'applied',
    location: 'Guildford',
    salary_range: '£34,000 – £40,000',
    job_url: 'https://www.baesystems.com/careers/graduate-software-engineer',
    notes: 'Requires SC clearance — 8 week lead time.',
    daysAgo: 9,
    progressDays: 0,
  },
  {
    company: 'Thales',
    role: 'Junior Systems Developer',
    status: 'applied',
    location: 'Reading',
    salary_range: '£36,000 – £42,000',
    job_url: null,
    notes: null,
    daysAgo: 8,
    progressDays: 0,
  },
  {
    company: 'Zego',
    role: 'Junior Full-Stack Engineer',
    status: 'applied',
    location: 'London (Hybrid)',
    salary_range: '£45,000 – £52,000',
    job_url: 'https://www.zego.com/careers/junior-full-stack-engineer',
    notes: 'Next.js and Python — closest match to my own stack.',
    daysAgo: 7,
    progressDays: 0,
  },
  {
    company: 'Multiverse',
    role: 'Graduate Software Engineer',
    status: 'applied',
    location: 'London',
    salary_range: '£44,000 – £50,000',
    job_url: 'https://www.multiverse.io/careers/graduate-software-engineer',
    notes: null,
    daysAgo: 6,
    progressDays: 0,
  },
  {
    company: 'Featurespace',
    role: 'Junior Data Engineer',
    status: 'applied',
    location: 'Cambridge',
    salary_range: '£42,000 – £48,000',
    job_url: 'https://www.featurespace.com/careers/junior-data-engineer',
    notes: 'Fraud detection models — overlaps with the ML side of this project.',
    daysAgo: 5,
    progressDays: 0,
  },
  {
    company: 'Onfido',
    role: 'Junior Backend Engineer',
    status: 'applied',
    location: 'London (Remote)',
    salary_range: '£48,000 – £55,000',
    job_url: 'https://onfido.com/careers/junior-backend-engineer',
    notes: null,
    daysAgo: 4,
    progressDays: 0,
  },
  {
    company: 'Tessian',
    role: 'Graduate Software Engineer',
    status: 'applied',
    location: 'London',
    salary_range: '£50,000 – £57,000',
    job_url: 'https://www.tessian.com/careers/graduate-software-engineer',
    notes: 'Applied the day it was posted.',
    daysAgo: 2,
    progressDays: 0,
  },
  {
    company: 'PA Consulting',
    role: 'Technology Graduate',
    status: 'applied',
    location: 'London',
    salary_range: '£35,000 – £41,000',
    job_url: null,
    notes: null,
    daysAgo: 1,
    progressDays: 0,
  },
];
